### ISSUE TITLE
Anything-but filter in the event source not working

### ISSUE THREAD

**Issue by ebarriosjr** [rubenkaiser/serverless-offline-eventBridge#94]
I have a case where I am adding:
```
  events: [
                {
                    eventBridge: {
                        pattern: {
                            'detail-type': ['item.detail'],
                            source: [{ 'anything-but': ['com.example.pepe'] }],
                        },
                    },
                },
            ],
```
But the messages sent with this source, are actually triggering my handler.

Is this a known bug?

**Comment by rubenkaiser** [comment]
Checking the code I believe to have found the bug. I've just published a beta version. Can you verify that this works properly?

```https://www.npmjs.com/package/serverless-offline-aws-eventbridge/v/2.2.3-beta.0```

**Comment by ebarriosjr** [comment]
Sadly no, the bug still persists. When I trigger the event I get into an infinite loop.

**Comment by rubenkaiser** [comment]
Are you sure you've installed the beta version?

```yarn add serverless-offline-aws-eventbridge@2.2.3-beta.0```

When I test this version with the following it works:

```
  consumeEvent:
    handler: events.consume
    events:
      - eventBridge:
          eventBus: marketing
          pattern:
            source: [{ 'anything-but': ['com.example.pepe'] }]
```

Sending events with the following:
```
// consumeEvent is subscribed
// consumeEvent successfully processed event with id xxxxxxxx-xxxx-xxxx-xxxx-1727873561298
 {
  EventBusName: 'marketing',
  Source: 'com.example.pepeNOT',
  DetailType: 'UserSignUp',
  Detail: `{ "E-Mail": "some@someemail.some" }`,
},
```

```
// consumeEvent is not subscribed
 {
  EventBusName: 'marketing',
  Source: 'com.example.pepe',
  DetailType: 'UserSignUp',
  Detail: `{ "E-Mail": "some@someemail.some" }`,
},
```

**Comment by rubenkaiser** [comment]
@ebarriosjr Did you figure this out?

**Comment by ebarriosjr** [comment]
Yes, I had to delete all my node_modules and reinstall and now it works. Thanks for looking into it.
